# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb969c2270dd6f5963df8f6ca41b6176313b875d44d7f526d6c7c6d245d2c5aec372b33a07592285f55e069dbe03b18d5a81373ee2e9782b93bdf1eac6783cce

test:
  secret_key_base: da6a6d0aff0093833195542081a966dbff64c54d79cf986f637b019d716e7a4c5fb361d7f8349d969a92fdaa689387a0916735b03467bca65700c9b135c10c65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
